version: 1.1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: LatticeObjectTree\bin\Release\*.nupkg
- path: LatticeObjectTree\bin\Release\net35\*.*
