version: 1.0.1.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: LatticeObjectTree\bin\Release\LatticeObjectTree.dll
- path: LatticeObjectTree\bin\Release\LatticeObjectTree.XML